<a href="https://colab.research.google.com/github/Jagannath8/100-Days-of-Uplift/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **100 Days of Uplift**

# Assignment 1

Ques:1: Write a program to reverse a NumPy array. 

(Create your own array using array() function of NumPy library)


In [ ]:
import numpy as np
arr = ([10, 20, 30, 40, 50])
print("Original array: ", arr)
rev = np.flip(arr)
print("Reversed array: ", rev)

Original array:  [10, 20, 30, 40, 50]
Reversed array:  [50 40 30 20 10]




---



Ques:2:Extract all odd numbers from arr. 

Input: arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd = arr[arr % 2 == 1]
print("Odd numbers", odd)

Odd numbers [1 3 5 7 9]




---



Ques:3:Convert a 1D array to a 2D array with 2 rows. 

Input: np.arange(10)

In [ ]:
a = np.arange(10)
print("1D array: ", a)
print("2D array: \n", np.reshape(a, (2, 5)))

1D array:  [0 1 2 3 4 5 6 7 8 9]
2D array: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]




---



Ques:4:Get the common items between a and b. 

Input: a = np.array([1,2,3,2,3,4,3,4,5,6]) ;

b = np.array([7,2,10,2,7,4,9,4,9,8])

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("Common items between a and b are: ", np.intersect1d(a, b))

Common items between a and b are:  [2 4]




---



Quest:5: Swap rows 1 and 2 in the array arr. 

Input:arr = np.arange(9).reshape(3,3) ;arr

In [ ]:
arr = np.arange(9).reshape(3,3)
print("Array is: \n", arr)
rev1 = np.flip(arr[0])
print("Reverse of row1: ", rev1)
rev2 = np.flip(arr[1])
print("Reverse of row1: ", rev2)

Array is: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Reverse of row1:  [2 1 0]
Reverse of row1:  [5 4 3]




---

